#:schema https://www.unpkg.com/wrangler/config-schema.json

compatibility_date = "2025-10-11"
name = "blog-hope"
send_metrics = false

[assets]
directory = "./src/.vuepress/dist"

[observability]
enabled = true

[placement]
mode = "smart"
