name: Deploy

on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Checkout Obsidian
        run: |-
          mkdir --parents --verbose "$HOME/.ssh"
          echo '${{ secrets.DEPLOY_KEY }}' > "$HOME/.ssh/deploy_key"
          echo '${{ vars.SSH_CONFIG }}' > "$HOME/.ssh/config"
          echo '${{ vars.SSH_KNOWN_HOSTS }}' > "$HOME/.ssh/known_hosts"
          chmod --verbose 'u=rw,go=' "$HOME/.ssh/deploy_key"
          git clone 'ssh://git@forgejo.liblaf.me/liblaf/obsidian.git' 'obsidian'
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Download Assets
        run: bash 'scripts/pre-build.sh'
        env:
          OBSIDIAN_VAULT_DIR: obsidian
      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build
      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dist
          path: src/.vuepress/dist

  deploy:
    name: Deploy
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Cloudflare
      url: https://hope.liblaf.me
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Download Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: dist
          path: src/.vuepress/dist
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
