name: Deploy

on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Checkout Obsidian
        run: |-
          mkdir --parents --verbose "$HOME/.ssh"
          echo '${{ secrets.DEPLOY_KEY }}' > "$HOME/.ssh/deploy_key"
          echo '${{ vars.SSH_CONFIG }}' > "$HOME/.ssh/config"
          echo '${{ vars.SSH_KNOWN_HOSTS }}' > "$HOME/.ssh/known_hosts"
          chmod --verbose 'u=rw,go=' "$HOME/.ssh/deploy_key"
          git clone 'ssh://git@forgejo.liblaf.me/liblaf/obsidian.git' 'obsidian'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install Dependencies
        run: |-
          corepack enable
          pnpm install --frozen-lockfile
      - name: Download Assets
        run: bash 'scripts/pre-build.sh'
        env:
          OBSIDIAN_VAULT_DIR: obsidian
      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: src/.vuepress/dist

  deploy:
    name: Deploy
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Cloudflare
      url: https://hope.liblaf.me
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: src/.vuepress/dist
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
